[build]
target = "riscv32imc-unknown-none-elf"

[target.riscv32imc-unknown-none-elf]
rustflags = [
  "-C", "link-arg=-Triscv_ulp_link_default.x",
]

[unstable]
build-std = ["core"]

[profile.release]
strip = true
lto = true
codegen-units = 1
opt-level = "z"
# FIXME: Panic should probably start main cpu?
panic = "abort"